benchmark = "job+ceb-imdb-full"
q_type = "q_compile"
init_lr = 3e-3
min_lr = 1e-7
weight_decay = 1e-2
epochs = 300
batch_size = 1024
num_workers = 28
lpe_size = 8
output_size = 128
vec_size = 16
n_layers = 4
hidden_dim = 256
activate = "relu"
gtn_n_layers = 3
gtn_n_heads = 4
gtn_dropout = 0.1
op_groups = ["type", "cbo", "op_enc", "hist", "bitmap"]
dropout = 0.1
pos_encoding_dim = 8
use_batchnorm = false
data_percentage = 30
benchmark_ext = "job-extv2"
ext_data_amount = 20000
loss_weights = [1, 0]
attention_layer_name = "GTN"
