path = "/home/guillaume/data/udao-spark-optimizer/job_100000x1+extv2_20000x1/q_compile/ea0378f56dcf_30_ext_20000/"
output_path = "/home/guillaume/data/training_results/job-extv2.parquet"
test_glob = "**/obj_df_job_original_with_test_latenc*.pkl"
base_path = "/home/guillaume/data/udao-spark-optimizer/job_100000x1+extv2_20000x1/q_compile/"

