llm = false
retry = 1
llm_model = "deepseek-r1:1.5b"
llm_base_prompt = """
    You are writing queries for a markdown text using \
    the format:```sql for correct formatting in markdown
    """
queries_path = "./data/generated_queries/TPCDS_FORMATTED_QUERIES"
total_queries = 5
seed = 42
dataset = "TPCDS"
destination_folder = "/home/mathos/phd/repos/query_generation/trunk/data/generated_queries/TPCDS_LLM"

[llm_prompts.self_join]
prompt = "write this query again only adding the ```sql for markdown"
weight = 30

[llm_prompts.outer_join]
prompt = "write this query again only adding the ```sql for markdown"
weight = 30