benchmark = "tpcds"
q_type = "q_compile"
# Training parameters
init_lr = 3e-3
min_lr = 1e-7
weight_decay = 1e-2
epochs = 300
batch_size = 1024
num_workers = 28
loss_weights = [1, 0]
# Regressor parameters
n_layers = 4
hidden_dim = 256
activate = "relu"
dropout = 0.1
# embedder parameters
attention_layer_name = "GTN"
output_size = 128
gtn_n_layers = 3
gtn_n_heads = 4
gtn_dropout = 0.1
vec_size = 16
lpe_size = 8
# Node encodings
op_groups = ["type", "cbo", "op_enc", "hist", "bitmap"]
pos_encoding_dim = 8
use_batchnorm = false
# fold = None
# tpcds ext
benchmark_ext = "tpcds-ext-sj-sf-llm"
ext_data_amount = 47391
# job ext
# ext_up_to_n_joins = None
