benchmark = "small-tpcds+job-selected"
q_type = "q_compile"
# training parameters
init_lr = 3e-3
min_lr = 1e-7
weight_decay = 1e-2
loss_weights = [1, 0]
epochs = 150
batch_size = 1024
num_workers = 28
# Graph model
output_size = 64
vec_size = 16
tcnn_hidden_dim = 256
lpe_size = 8
# Regressor params
dropout = 0.1
n_layers = 4
hidden_dim = 256
activate = "relu"
# Node encodings
op_groups = ["type", "cbo", "op_enc", "hist", "bitmap"]
pos_encoding_dim = 8
use_batchnorm = false
# fold = None
benchmark_ext = "tpcds-ext-sj-sf-llm-filtered-llm"
ext_data_amount = 48093
